language: c

compiler: gcc

dist: xenial
sudo: required

addons:
  apt:
    packages:
      - gfortran
      - libboost-all-dev
      - python-dev
      - qt5-default
      - swig

before_script:
  - mkdir ./build
  - pushd ./build
  - cmake
    -DBUILD_HelloBoost=ON
    -DBUILD_HelloC=ON
    -DBUILD_HelloCXX=ON
    -DBUILD_HelloFortran=ON
    -DBUILD_HelloPythonC=ON
    -DBUILD_HelloPythonCXX=ON
    -DBUILD_HelloPythonSWIG=ON
    -DBUILD_HelloQt=ON
    ..
  - popd

script:
  - pushd ./build
  - cmake --build .
  - ctest -V
  - popd
