language: c

compiler: gcc

dist: xenial
sudo: required

addons:
  apt:
    packages:
      - gfortran
      - python-dev
      - qt5-default
      - swig

# https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

before_script:
  - mkdir ./build
  - pushd ./build
  - cmake
    -DBUILD_HelloC=ON
    -DBUILD_HelloCXX=ON
    -DBUILD_HelloFortran=ON
    -DBUILD_HelloPythonC=ON
    -DBUILD_HelloPythonCXX=ON
    -DBUILD_HelloPythonSWIG=ON
    -DBUILD_HelloQt=ON
    ..
  - popd

script:
  - cmake --build ./build
  - ctest -V ./build
