language: c

compiler: gcc

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - cmake
      - gfortran
      - libboost-all-dev
      - libinsighttoolkit4-dev
      - libopenmpi-dev
      - libvtk5-dev
      - nvidia-cuda-toolkit
      - openmpi-bin
      - python-dev
      - qt4-dev-tools
      - swig

# https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

before_script:
  - mkdir build
  - cd build
  - cmake
    -DBUILD_HelloBoost=ON
    -DBUILD_HelloC=ON
    -DBUILD_HelloCUDA=ON
    -DBUILD_HelloCXX=ON
    -DBUILD_HelloFortran=ON
    -DBUILD_HelloITK=ON
    -DBUILD_HelloMPI=ON
    -DBUILD_HelloPythonC=ON
    -DBUILD_HelloPythonCXX=ON
    -DBUILD_HelloPythonSWIG=ON
    -DBUILD_HelloQt4=ON
    -DBUILD_HelloVTK=ON
    ..

script:
  - make
  - make test ARGS="--extra-verbose"
