language: c

compiler: gcc

dist: xenial
sudo: required

env:
  - CMAKE_VERSION=3.14.3

addons:
  apt:
    packages:
      - gfortran
      - python-dev
      - qt5-default
      - swig

# https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

before_script:
  - wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.tar.gz
  - tar xf cmake-$CMAKE_VERSION.tar.gz
  - pushd cmake-$CMAKE_VERSION
  - ./bootstrap
  - make
  - sudo make install
  - popd
  - mkdir build
  - pushd build
  - cmake
    -DBUILD_HelloC=ON
    -DBUILD_HelloCXX=ON
    -DBUILD_HelloFortran=ON
    -DBUILD_HelloPythonC=ON
    -DBUILD_HelloPythonCXX=ON
    -DBUILD_HelloPythonSWIG=ON
    -DBUILD_HelloQt=ON
    ..

script:
  - cmake --build
  - ctest -V .
