name: CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - name: Run sudo apt-get install ...
        run: >-
          sudo apt-get install
          build-essential
          gfortran
          libboost-all-dev
          mpi-default-bin
          mpi-default-dev
          python3-dev
          qt5-default
          swig
      - run: cmake --version
      - name: Run cmake -S . -B ./build ...
        run: >-
          cmake -S . -B ./build
          -DBUILD_HelloBoost=ON
          -DBUILD_HelloC=ON
          -DBUILD_HelloCUDA=OFF
          -DBUILD_HelloCXX=ON
          -DBUILD_HelloEnvironment=ON
          -DBUILD_HelloFortran=ON
          -DBUILD_HelloMATLAB=OFF
          -DBUILD_HelloMPI=ON
          -DBUILD_HelloPythonC=ON
          -DBUILD_HelloPythonCSWIG=ON
          -DBUILD_HelloPythonCXX=ON
          -DBUILD_HelloPythonCXXSWIG=ON
          -DBUILD_HelloQt=OFF
      - run: cmake --build ./build
      - run: cmake --build ./build --target test_verbose
